
/*异常处理：
1、 runtime异常：程序员--抛出   vs JVM--自动处理
 2、checked异常：程序员--抛出  vs 程序员---手动处理
 
 checked异常处理：
 1、程序员手动处理异常之一：throws
 2、程序员手动异常处理之二：try catch finally 

*/

//自定义checked异常：继承
class FuException extends Exception{
	public FuException(){}
	public FuException(String message){
		super(message);
	}
}

class Demo{
/*
	                   判断异常----------------抛出异常--------------处理异常 
runtime			              代码								jvm
checked   ================程序员处理===================
分离
 */
	
	public void run(int[] arr,int index){
		if(arr==null){
			throw new NullPointerException("JVM：空指针异常");
		}
		if(index>=arr.length){
			throw new ArrayIndexOutOfBoundsException("JVM:index大于了数组的长度");
		}
	}
}

public class DiyTest {
	public static void main(String[] args) {
		

	}

}
